
[package]
name = "treecore_simu"
version = "0.0.1"
authors = ["maksyuki <maksyuki@126.com>"]
edition = '2021'

[dependencies]
clap = {version = "^3.1", features = ["derive"]}
tungstenite = "0.17.2"
object = "0.28.4"