name: unit-test

on:
  push:
    branches: [ main, dev, feat-parser ]

jobs:
  unit-test-tgt:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: parser test
        run: |
          cd src/parser
          cargo test --lib